version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    depends_on:
      - postgres
    environment:
      # SPRING_PROFILES_ACTIVE: test
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cfreminder
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: P@ssw0rd
      TZ: Asia/Bangkok
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    # ports:
    #   - "8080:8080"
    expose:
      - "8080"
    networks:
      - app-network

  postgres:
    image: postgres:16-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: cfreminder
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: P@ssw0rd
      TZ: Asia/Bangkok
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_script:/docker-entrypoint-initdb.d
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro # สำหรับ SSL
    networks:
      - app-network
    depends_on:
      app:
        condition: service_healthy

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
