spring.application.name=cfreminder
app.timezone=GMT+7
app.base-url=${APP_BASE_URL:http://localhost:8080}
#spring.profiles.active=dev

## DATASOURCE ##
spring.datasource.url=jdbc:${JDBC_DATABASE_URL}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.configuration.maximum-pool-size=30

## LINE CONFIG ##
line.bot.channel-secret=${LINE_CB_SECRET}
line.bot.channel-token=${LINE_CB_TOKEN}
line.bot.handler.path=/callback

## GEMINI ##
google.genai.api-key=${GEMINI_API_KEY}
