spring.application.name=cfreminder

## DATASOURCE ##
spring.datasource.url=jdbc:postgresql://localhost:5432/cfreminder
spring.datasource.username=admin
spring.datasource.password=P@ssw0rd
spring.datasource.configuration.maximum-pool-size=30

## LINE CONFIG ##
line.bot.channel-secret=5d00919d468914129d9f43110b26968e
line.bot.channel-token=dkIjvHcLzBZ8EASoTDbviCc3KhSjEx2De6zR02z4FRqMkrpxdtZOH7lNcLENhyhf4c4YB6zPBAjcohfLnuvG1CQ8T3yD9Rw8z9wSvs+H+z1HH2L4wN90aILdqL5wLMMUxH8w1jQ+h/SRsp+e6a+hfgdB04t89/1O/w1cDnyilFU=
line.bot.handler.path=/callback
